# General information
discord_server_id: 543338931022856242
token: Njg5MDIwNjQxNzM5MTQ1MjM2.XrUu_A.NksDEd7vVaIf9cNEI1_XZ0jJgqo
discord_channel_id: ~

# Clear information
clear_roles: false
clear_channels: false
channels_to_ignore: ~
roles_to_ignore: ~