STAFF_EPILOGIN:
  name: Staff Epilogin
  color: ffff4d
  hoist: true
  permissions: ADMIN_PERM
  mentionable: true

ADMIN:
  name: Admin
  color: ffff4d
  hoist: true
  permissions: ADMIN_PERM
  mentionable: true

MODO:
  name: Modo
  color: ff6600
  hoist: true
  permissions: MODO_PERM
  mentionable: true

ACDC: 
  name: ACDC
  color: b34700
  hoist: true
  permissions: MANAGE_MESSAGE
  mentionable: true


# Class

A1:
  name: A1
  color: b34700
  hoist: true
  mentionable: true

A2:
  name: A2
  color: b34700
  hoist: true
  mentionable: true

B1:
  name: B1
  color: b34700
  hoist: true
  mentionable: true

B2:
  name: B2
  color: b34700
  hoist: true
  mentionable: true

C1:
  name: C1
  color: b34700
  hoist: true
  mentionable: true

C2:
  name: D2
  color: b34700
  hoist: true
  mentionable: true

D1:
  name: D1
  color: b34700
  hoist: true
  mentionable: true

D2:
  name: D3
  color: b34700
  hoist: true
  mentionable: true

INT1:
  name: INT1
  color: b34700
  hoist: true
  mentionable: true

INT2:
  name: INT2
  color: b34700
  hoist: true
  mentionable: true

INT3:
  name: INT3
  color: b34700
  hoist: true
  mentionable: true